GET http://localhost:3000/

###
GET http://localhost:3000/movies
Content-Type : aplication/json

###
GET http://localhost:3000/movies/10
Content-Type : aplication/json


###
DELETE http://localhost:3000/movies/delete/9
Content-Type : aplication/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjI0NTYxNzUwLCJleHAiOjE2MjQ2NDgxNTB9.aqQSM3_cmLPb3PYE1N2bazb9IWJ8_Vkb-dFmzyVSmsk

###
GET http://localhost:3000/characters/1
Content-Type : aplication/json

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"gabrielpelizzapd@gmail.com",
    "pass":"38458895"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"loremipsum@gmail.com",
    "pass":"xxxxxx"
}